name: Create and Upload Apk on Firebase App Distribution.

on:
  push:
    branches: [ main ]

jobs:
  # Job 1 ->
  CI-Prod:
    name: Apk uploading on Firebase App Distribution
    runs-on: ubuntu-latest

    # Step 1 Store all required keys in environment variable
    env:
      FIREBASE_CLI_TOKEN: ${{secrets.FIREBASE_TOKEN}}
      FIREBASE_APP_ID: ${{secrets.FIREBASE_APP_ID}}
      ANDROID_KEY_ALIAS: ${{secrets.RELEASE_KEY_ALIAS}}
      ANDROID_KEY_PASSWORD: ${{secrets.RELEASE_KEY_PASSWORD}}
      ANDROID_STORE_PASSWORD: ${{secrets.RELEASE_STORE_FILE}}
      ANDROID_SIGNING_KEY: ${{secrets.KEYSTORE_BASE64}}
      PRIVATE_SERVICE_ACCOUNT_KEY: ${{secrets.PRIVATE_SERVICE_ACCOUNT_KEY}}

    steps:
      # Step 2 Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 3 Setup JDK
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Step 4 Setup Ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.3'

      # Step 5 Install the bundler & Fastlane (Create environment for ruby to avoid dependency hell and manage the dependencies versions)
      - name: Install bundler
        run: |
          gem install bundler:2.2.27
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      # Step 6 Install the Firebase app distribution plugin with fastlane
      - name: Install Firebase app distribution plugin
        run: bundle exec fastlane add_plugin firebase_app_distribution firebase_app_distribution_login

      # Step 7 Run the Base64 command to decode our PRIVATE_SERVICE_ACCOUNT_KEY and create the private-decoded-key.json file of our service account
      - name: Generate google-services.json file
        run: echo ${{secrets.PRIVATE_SERVICE_ACCOUNT_KEY}} | base64 -d > /home/runner/work/_temp/google-services.json

      # Step 8 Grant execute permission to gradlew
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      # Step 9 Run the Base64 command to decode and create the .jks file from base64 string of .jks
      - name: Generate .jks file
        run: echo ${{secrets.ANDROID_SIGNING_KEY}} | base64 -d > /home/runner/work/_temp/pokedex_keystore.jks

      # Step 10 Run the fastlane command to upload the build
      - name: Upload Apk to Firebase
        run: bundle exec fastlane build_and_upload_apk_with_auth
