name: Android CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build and Test
        run: ./gradlew check

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: app/build/outputs/apk/release/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v2
        with:
          name: app-release
          path: app/build/outputs/apk/release/

      - name: Display Contents of APK Directory
        run: ls -R app/build/outputs/apk/release

      - name: Install Firebase CLI
        run: |
          sudo npm install -g firebase-tools

      - name: Authenticate with Firebase
        run: |
          echo ${{ secrets.CREDENTIAL_FILE_CONTENT }} > /tmp/firebase-credentials.json
          firebase auth:activate-service-account --token "${{ secrets.FIREBASE_TOKEN }}" /tmp/firebase-credentials.json

      - name: Deploy to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFile: /tmp/firebase-credentials.json
          groups: 'main-group'
          file: 'app/build/outputs/apk/release/app-release-unsigned.apk'
