name: Android CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build and Test
        run: ./gradlew check

      - name: Build Release APK
        run: ./gradlew assembleRelease

  # Sign and deploy the release APK
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Decode keystore from base64
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks

      - name: Sign APK
        uses: android-actions/sign@v3
        with:
          release-directory: 'app/build/outputs/apk/release'
          keystore-path: './keystore.jks'
          keystore-alias: ${{ secrets.RELEASE_KEY_ALIAS }}
          keystore-password: ${{ secrets.RELEASE_STORE_PASSWORD }}
          key-password: ${{ secrets.RELEASE_KEY_PASSWORD }}
          apk-path: 'app/build/outputs/apk/release/app-release.apk'

      - name: Deploy to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFile: ${{ secrets.FIREBASE_CREDENTIALS_FILE }}
          groups: 'main-group'
          file: 'app/build/outputs/apk/release/app-release.apk'
