name: Android CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set execute permissions for gradlew
      run: chmod +x ./gradlew

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build and Test
      run: ./gradlew check

    - name: Build Release APK
      run: ./gradlew assembleRelease

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Firebase App Distribution
      uses: w9jds/firebase-action@v2
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }}
        token: ${{ secrets.FIREBASE_TOKEN }}
        groups: 'main-group'
        file: 'app/build/outputs/apk/release/app-release.apk'